#!/bin/bash

echo
SELF_NAME=`basename "$0"`
MACRO_NAME="${SELF_NAME/-/.}"
CMD_NAME="$1"
SCRIPT_DIR_BASH="$(readlink -f `dirname $0`)"
SCRIPT_DIR_WIN="${SCRIPT_DIR_BASH/#\/c/\C:}"
CURRENT_DIR_WIN="${PWD/#\/c/\C:}"

PowerShell.exe -NoProfile -ExecutionPolicy Bypass -File "$SCRIPT_DIR_WIN/run_dev_macro.ps1" -macroName "$MACRO_NAME" -cmd "$CMD_NAME" -repoDir "$CURRENT_DIR_WIN" < /dev/null
git status

if [ "$CURRENT_DIR_WIN" == "$SCRIPT_DIR_WIN" ] 
	then
		echo
		echo "NOTE! Can't copy Word template that is running code. Do it manually!"
fi