#!/bin/sh
# Runs macro with Module.Function format if this script is named Module-Function.
# bonus, if you use hyphen in script and add to PATH, you can run as that program
SELF_NAME=`basename "$0"`
MACRO_NAME="${SELF_NAME/-/.}"
SCRIPT_DIR_BASH="$(readlink -f `dirname $0`)"
SCRIPT_DIR_WIN="${SCRIPT_DIR_BASH/#\/c/\C:}"

PowerShell -NoProfile -ExecutionPolicy Bypass -Command "C:/Users/erica.warren/Documents/GitHub/vba_devtools/run_dev_macro.ps1 -macroName $MACRO_NAME -repoDir ${PWD/#\/c/\C:}" < /dev/null
git status
